### ISSUE TITLE
is it possible to disable drag function in initHandler?

### ISSUE THREAD

**Issue by tegarnugroho** [Mindinventory/progressive_time_picker#1]
I want to make one of the handlers disabled so that it cannot change the position of the handler.

**Comment by mohit-chauhan-mi** [comment]
> I want to make one of the handlers disabled so that it cannot change the position of the handler.

@skripsimu to achieve this you can use isInitHandlerSelectable or isEndHandlerSelectable parameters of TimePicker to enabled or disabled the selection of handler.
