### ISSUE TITLE
Update selected time scale programmatically.

### ISSUE THREAD

**Issue by ShyshkovOleg** [Mindinventory/progressive_time_picker#10]
Hi, Is there a way to update time scale programmatically? 
When I try to update them, nothing happens.
`setState(() {
    _inBedTime = PickedTime(h: 13, m: 0);
    _outBedTime = PickedTime(h: 18, m: 0);
})
`
On the other hand time format update correctly inside setState.

**Comment by dragonfire1975** [comment]
Hello Together, does it work? For me update does not work.

**Comment by mohit-chauhan-mi** [comment]
Implemented this, please check it with the latest [version](https://pub.dev/packages/progressive_time_picker/versions/0.0.9). Thanks.

**Comment by dragonfire1975** [comment]
Hello Mohit,

thanks for the fix it works. I also added a pull request regarding Scaling of the decoration numbers.
I used the scalefactor to adjust the positioning like descriped in the comment of the variable. 
Can you confirm the pull request, so i can use your time picker.


Mit freundlichen Grüßen / Best Regards
_______________________________________
Keller-automation

Christian Keller
Albert-Schweitzer-Strasse 17

D-68723 Schwetzingen

email: ***@***.*** ***@***.***>
Tel.: +49 176 62174859
