### ISSUE TITLE
stop dragging the picker when it reaches the disabled time !

### ISSUE THREAD

**Issue by mohamedsl22** [Mindinventory/progressive_time_picker#13]
the behavior that I get when the user reaches the disabled time which is in my case from 23:59 to 00:00 instead of stoping the picker there it skips it and start a new picker that starts from 00:00, what I want is that to stop the picker on 23:59 instead of skipping it and starts new picker from 00:00.
can you please fix it 🙏🏻
thank you

**Comment by abrarmalekji345** [comment]
Hi @mohamedsl22, This is our intended behaviour so the user can reset the range once it has reached the 12-hour cycle. Thanks.
