### ISSUE TITLE
Gap at the top of circle

### ISSUE THREAD

**Issue by jonashoelzel** [Mindinventory/progressive_time_picker#15]
When making the circle larger then 300px a little gap appears at the top of the circle:
 
![image](https://github.com/Mindinventory/progressive_time_picker/assets/74920901/dfe456d7-dbd8-44f6-b098-0bd53b0bf64f)

Can you fix this?

**Comment by mi-raj04** [comment]
@jonashoelzel  solve issue in [https://pub.dev/packages/progressive_time_picker] version
