### ISSUE TITLE
There is a bug where _outBedTime can be set to 00H~01H when _disabledInitTime 0H

### ISSUE THREAD

**Issue by 2ChanWoo** [Mindinventory/progressive_time_picker#16]
First, thank you for creating this package :)

There is a bug where _outBedTime can be set to 00:00 ~ 01:00 when _disabledInitTime = PickedTime(h: 0, m: 0);!

**Comment by mohit-chauhan-mi** [comment]
Closing this issue for now. Please reopen it with more details if needed.
