### ISSUE TITLE
Questions and clarifications

### ISSUE THREAD

**Issue by NightSkyDev** [Mindinventory/progressive_time_picker#2]
First, thank you for providing such a great time picker!  I'm looking forward to sending you the link for my app when it's done.

Second, some questions:

1) Is it possible to limit the secondarySectors to only show within the active time?  I'm trying to find away to make custom markers on the clock.  I want to show reminder times during the active/awake time.

2) Is it possible to change the time increment when dragging the start/stop handles?  I find it really hard to get the handle to stop at the right time - like instead of 6:00 it's 5:55 or 6:05.

3) Is it possible to change the secondarySectors to be double instead of an int? In other words, I want to use minutes instead of whole hours.  (Or is there another way to accomplish this?)

**Comment by mohit-chauhan-mi** [comment]
Hey @NightSkyDev We've published the new version (0.0.5) of this package.

We've added support of time increment feature named ClockIncrementTimeFormat inside the TimePickerClockNumberDecoration using this we're able to add time increment using the following values 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, and 60.

And as of now question 1 and 3 is not possible but will do our best to add support for that.
Thanks for using our package and your feedback.
