### ISSUE TITLE
Request for new functionality

### ISSUE THREAD

**Issue by Phantom586** [Mindinventory/progressive_time_picker#3]
Thanks for providing such awesome, customizable and easy to use time picker.

Functionality Request:
> to be able to mark specific time ranges disabled and enabled for selection. For Ex:- suppose between (12 - 3 am), I want to disable time range (1 - 1:30 am), such that user won't be able to select this specific time range, only the remaining time ranges that are (12 - 1 am and 1:30 - 3 am).

**Comment by meet-mi** [comment]
Now you can install new version with requested functionality, check our [latest version (0.0.7)](https://pub.dev/packages/progressive_time_picker)
