### ISSUE TITLE
[Bug] onSelectionEnd was not triggered when bothHandler moves

### ISSUE THREAD

**Issue by akurnaz** [Mindinventory/progressive_time_picker#5]
Thank for the plugin.
I use the onSelectionEnd callback function to get final value. When I drag and drop the middle bar, it was not triggered. Especially it becomes more visible while clockIncrementTimeFormat is SIXTYMIN. 

I debugged, I realize that when isPanEnd variable is true, newValueInit value is still the same as widget.init value. I hope that helpful. 

https://user-images.githubusercontent.com/7497369/203127409-f4a0f43b-51dd-4b19-89f1-f90cda23b393.mov

Plugin version: 0.0.7
Device: Iphone 11 emulator, IOS 16.1

**Comment by mohit-chauhan-mi** [comment]
@akurnaz Check with the [latest version](https://pub.dev/packages/progressive_time_picker/versions/0.0.8) for this.
