### ISSUE TITLE
Input should not move inside the disabledRange

### ISSUE THREAD

**Issue by cedvdb** [Mindinventory/progressive_time_picker#6]
This is a bit subjective but I believe, from an UX standpoint, that the handlers should not move inside the disabled range at all. 

Adding an option to disable going into that range would be nice.

**Comment by abrarmalekji345** [comment]
Hi, @cedvdb the behaviour you suggested can restrict the user from moving their selection range ahead of the disabled range.
i.e. disabled time is 11:00 to 12:00, and selection time is 00:00 to 05:00. suppose you want to move the handler from 13:00 to 14:00.
