### ISSUE TITLE
Prefer start handler on top for same hour selection

### ISSUE THREAD

**Issue by cedvdb** [Mindinventory/progressive_time_picker#7]
When the start handler and the end handler are on top of each other, the end handler is show, but the start handler is the one that actually moves. 

![image](https://user-images.githubusercontent.com/22280985/209483739-c7b4667d-a972-4c8f-beb7-1bb6afd511c3.png)

Imo, the start handler should be shown because it is selecting a whole day range, and the icon for start would be more appropriate

**Comment by mohit-chauhan-mi** [comment]
@cedvdb You may use ```drawInitHandlerOnTop <- TimePicker``` bool flag to achive this.
