### ISSUE TITLE
Mouse cursor for web on handlers

### ISSUE THREAD

**Issue by cedvdb** [Mindinventory/progressive_time_picker#8]
The cursor behavior on web is a bit unexpected, usually when an action can "change" something, the cursor reflects that. I believe `SystemMouseCursors.click` would be appropriate for the handlers

**Comment by mohit-chauhan-mi** [comment]
@cedvdb You may use ```mouseCursorForWeb <- TimePickerDecoration``` to achieve this with [latest version](https://pub.dev/packages/progressive_time_picker/versions/0.0.8).
