### ISSUE TITLE
[BUG/Enhancement] Disable dragging both handlers

### ISSUE THREAD

**Issue by lucariojb** [Mindinventory/progressive_time_picker#9]
Even if the selectable property of one handler is false it can be moved when moving both handlers at the same time (by dragging the highlited timespan).

Don't know if this is wanted, but I'd love to be able to disable this.

Thanks!

**Comment by mohit-chauhan-mi** [comment]
Implemented this, please check it with the latest [version](https://pub.dev/packages/progressive_time_picker/versions/0.0.9). Thanks.
